/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maffek;

/**
 *
 * @author rokun
 */
public class Klawisze extends javax.swing.JPanel {

    /**
     * Creates new form Klawisze
     */
    public Klawisze() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeden = new javax.swing.JButton();
        dwa = new javax.swing.JButton();
        trzy = new javax.swing.JButton();
        cztery = new javax.swing.JButton();
        piec = new javax.swing.JButton();
        szesc = new javax.swing.JButton();
        W = new javax.swing.JButton();
        A = new javax.swing.JButton();
        S = new javax.swing.JButton();
        D = new javax.swing.JButton();
        R = new javax.swing.JButton();
        C = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        R_opis = new javax.swing.JLabel();
        C_opis = new javax.swing.JLabel();
        N_opis = new javax.swing.JLabel();
        O_opis = new javax.swing.JLabel();
        robot_opis = new javax.swing.JLabel();
        WSAD_opis = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);

        jeden.setBackground(new java.awt.Color(0, 153, 0));
        jeden.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        jeden.setForeground(new java.awt.Color(255, 255, 255));
        jeden.setText("1");
        jeden.setToolTipText("");
        jeden.setMaximumSize(new java.awt.Dimension(40, 25));
        jeden.setMinimumSize(new java.awt.Dimension(25, 25));
        jeden.setPreferredSize(new java.awt.Dimension(50, 50));

        dwa.setBackground(new java.awt.Color(0, 153, 0));
        dwa.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        dwa.setForeground(new java.awt.Color(255, 255, 255));
        dwa.setText("2");
        dwa.setToolTipText("");
        dwa.setPreferredSize(new java.awt.Dimension(50, 50));

        trzy.setBackground(new java.awt.Color(0, 153, 0));
        trzy.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        trzy.setForeground(new java.awt.Color(255, 255, 255));
        trzy.setText("3");
        trzy.setToolTipText("");
        trzy.setPreferredSize(new java.awt.Dimension(50, 50));

        cztery.setBackground(new java.awt.Color(0, 153, 0));
        cztery.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        cztery.setForeground(new java.awt.Color(255, 255, 255));
        cztery.setText("4");
        cztery.setToolTipText("");
        cztery.setPreferredSize(new java.awt.Dimension(50, 50));

        piec.setBackground(new java.awt.Color(0, 153, 0));
        piec.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        piec.setForeground(new java.awt.Color(255, 255, 255));
        piec.setText("5");
        piec.setToolTipText("");
        piec.setPreferredSize(new java.awt.Dimension(50, 50));

        szesc.setBackground(new java.awt.Color(0, 153, 0));
        szesc.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        szesc.setForeground(new java.awt.Color(255, 255, 255));
        szesc.setText("6");
        szesc.setToolTipText("");
        szesc.setPreferredSize(new java.awt.Dimension(50, 50));

        W.setBackground(new java.awt.Color(255, 0, 0));
        W.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        W.setForeground(java.awt.Color.white);
        W.setText("W");
        W.setEnabled(false);
        W.setPreferredSize(new java.awt.Dimension(50, 50));

        A.setBackground(new java.awt.Color(255, 0, 0));
        A.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        A.setForeground(java.awt.Color.white);
        A.setText("A");
        A.setEnabled(false);
        A.setPreferredSize(new java.awt.Dimension(50, 50));

        S.setBackground(new java.awt.Color(255, 0, 0));
        S.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        S.setForeground(java.awt.Color.white);
        S.setText("S");
        S.setEnabled(false);
        S.setPreferredSize(new java.awt.Dimension(50, 50));

        D.setBackground(new java.awt.Color(255, 0, 0));
        D.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        D.setForeground(java.awt.Color.white);
        D.setText("D");
        D.setEnabled(false);
        D.setPreferredSize(new java.awt.Dimension(50, 50));

        R.setBackground(new java.awt.Color(0, 153, 0));
        R.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        R.setForeground(java.awt.Color.white);
        R.setText("R");
        R.setPreferredSize(new java.awt.Dimension(50, 50));

        C.setBackground(new java.awt.Color(0, 153, 0));
        C.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        C.setForeground(java.awt.Color.white);
        C.setText("C");
        C.setPreferredSize(new java.awt.Dimension(50, 50));

        N.setBackground(new java.awt.Color(0, 153, 0));
        N.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        N.setForeground(java.awt.Color.white);
        N.setText("N");
        N.setPreferredSize(new java.awt.Dimension(50, 50));

        O.setBackground(new java.awt.Color(255, 0, 0));
        O.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        O.setForeground(java.awt.Color.white);
        O.setText("O");
        O.setEnabled(false);
        O.setPreferredSize(new java.awt.Dimension(50, 50));

        R_opis.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        R_opis.setForeground(java.awt.Color.white);
        R_opis.setText("Resetowanie kamery");

        C_opis.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        C_opis.setForeground(java.awt.Color.white);
        C_opis.setText("Resetowanie robota");

        N_opis.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        N_opis.setForeground(java.awt.Color.white);
        N_opis.setText("Rozpoczecie nagrywania");

        O_opis.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        O_opis.setForeground(java.awt.Color.white);
        O_opis.setText("Odtworzenie nagranej trajektorii");

        robot_opis.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        robot_opis.setForeground(java.awt.Color.white);
        robot_opis.setText("Wybór czesci robota:");

        WSAD_opis.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        WSAD_opis.setForeground(java.awt.Color.white);
        WSAD_opis.setText("Klawisze sterujace:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jeden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(trzy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cztery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(piec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(szesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(robot_opis, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C_opis)
                                .addGap(30, 30, 30)
                                .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R_opis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(O_opis)
                            .addComponent(N_opis)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(WSAD_opis)))
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(robot_opis)
                    .addComponent(WSAD_opis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jeden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(trzy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_opis)
                                    .addComponent(N_opis))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C_opis)
                                    .addComponent(O_opis))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cztery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(szesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton A;
    public javax.swing.JButton C;
    private javax.swing.JLabel C_opis;
    public javax.swing.JButton D;
    public javax.swing.JButton N;
    private javax.swing.JLabel N_opis;
    public javax.swing.JButton O;
    private javax.swing.JLabel O_opis;
    public javax.swing.JButton R;
    private javax.swing.JLabel R_opis;
    public javax.swing.JButton S;
    public javax.swing.JButton W;
    private javax.swing.JLabel WSAD_opis;
    public javax.swing.JButton cztery;
    public javax.swing.JButton dwa;
    public javax.swing.JButton jeden;
    public javax.swing.JButton piec;
    private javax.swing.JLabel robot_opis;
    public javax.swing.JButton szesc;
    public javax.swing.JButton trzy;
    // End of variables declaration//GEN-END:variables
}
